### ISSUE TITLE
Unnecessary condition on GetVsixVersion

### ISSUE THREAD

**Issue by sharwell** [tom-englert/VSIX-SdkProjectAdapter#1]
The `Condition` attribute on this target can be removed since the target is only explicitly called:

https://github.com/tom-englert/VSIX-SdkProjectAdapter/blob/5994b555f94f5e5b780b3bbf752954658aa59e08/build/VSIX-SdkProjectAdapter.targets#L10

**Comment by tom-englert** [comment]
Just wanted to make sure that if s.o. already has a target with the same name in his project, he can switch off this one to avoid conflicts.
